name: Testiranje_aplikacije

on: [push, pull_request]

jobs:
  testiranje:
    runs-on: ubuntu-latest

    steps:
      - name: Kloniranje repozitorijuma
        uses: actions/checkout@v3

      - name: Postavljanje Python okruženja
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instaliranje paketa
        run: |
          pip install pytest

      - name: Pokretanje testova za prijavu
        run: pytest tests/test_prijava.py

      - name: Pokretanje testova za programe
        run: pytest tests/test_program.py

      - name: Pokretanje testova za  tabele
        run: pytest tests/test_tabele.py
